version: '3.8'

services:
  kiosklayso-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kiosklayso-web
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      # Sửa đường dẫn CSDL tương ứng trên server của bạn
      - DATABASE_URL=postgresql://root:root%40123@192.168.3.98:5433/kios?schema=public
      # Tên miền (hoặc IP Public) để bệnh nhân quét QR lấy số (VD: http://192.168.1.50:3000)
      - NEXT_PUBLIC_SERVER_URL=https://htqlbenhvien.bvdklangson.com.vn:201/kios
      # Thời gian chờ hiển thị số trước khi reset về trang chính (Tính bằng mili-giây, mặc định 3000 = 3s)
      - NEXT_PUBLIC_KIOSK_RESET_DELAY=3000
    # Nếu PostgreSQL cũng chạy bằng Docker trên server thì kết nối qua cùng network
    # networks:
    #   - your_app_network

# networks:
#   your_app_network:
#     external: true
